variables:
  TAG_BASE: 0.93.0-sts

stages:
 - prepare
 - build
 - test
 - publish

.go-base:
  image: 
    name: goreleaser/goreleaser:v1.24.0
    entrypoint: [""]
  before_script:
    - export GOPATH="$CI_PROJECT_DIR/.cache"
  cache:
    paths:
      - .cache

prepare:
  stage: prepare
  extends: .go-base
  script:
    - mkdir -p .cache
    - make -j2 gomoddownload
    - make install-tools

build:
  stage: build
  extends: .go-base
  script:
    - make otelcontribcol
  artifacts:
    paths:
      - bin/
    untracked: false
    expire_in: 30 days

test:
  stage: test
  extends: .go-base
  script:
    - make -C exporter/stackstateexporter test

publish:
  stage: publish
  extends: .go-base
  script:
    - make docker-otelcontribcol
    - COMMIT_COUNT=$(git rev-list --count HEAD)
    - DOCKER_TAG=$([ "${CI_COMMIT_BRANCH}" = "main" ] && echo ${TAG_BASE}-${CI_COMMIT_SHA} || echo ${TAG_BASE}-${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA})
    - docker tag otelcontribcol:latest ${DOCKER_REGISTRY}/stackstate/opentelemetry-collector-contrib:${DOCKER_TAG}
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "$DOCKER_REGISTRY"
    - docker push ${DOCKER_REGISTRY}/stackstate/opentelemetry-collector-contrib:${DOCKER_TAG}
  services:
    - name: docker:19.03.12-dind
      command:
        - --experimental
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_REGISTRY: quay.io
    DOCKER_USERNAME: $quay_user
    DOCKER_PASSWORD: $quay_password

